"use client";

import { useEffect, useState } from "react";

type Contribution = { id: string; submissionType: string; recordType: string; itemName: string; category: string; description?: string; quantity?: number; quantityUnit?: string; latitude: number; longitude: number; gpsAccuracy?: number; contactName: string; contactMethod: string; contactValue: string; photoKey: string; status: string; submittedAt: number };

export default function ModerationQueue() {
  const [items, setItems] = useState<Contribution[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  async function load() { setLoading(true); const response = await fetch("/api/contributions"); const data = await response.json(); setItems(data.contributions || []); setLoading(false); }
  useEffect(() => { load(); }, []);
  async function decide(item: Contribution, decision: "approved" | "rejected") { const note = document.querySelector<HTMLTextAreaElement>(`#note-${item.id}`)?.value || ""; setMessage(`${decision === "approved" ? "Approving" : "Rejecting"} ${item.itemName}…`); const response = await fetch(`/api/contributions/${item.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ decision, note }) }); const data = await response.json(); setMessage(response.ok ? `Submission ${decision}.` : data.error || "Review failed."); if (response.ok) await load(); }
  const pending = items.filter((item) => item.status === "pending"); const history = items.filter((item) => item.status !== "pending");
  return <section className="moderation"><div className="moderation-head"><div><div className="eyebrow dark"><span/> COMMUNITY REVIEW</div><h2>Public submissions</h2><p>Contact details are staff-only. Approval publishes new mapped records; stock reports remain an audited notice for staff action.</p></div><b className="pending-count">{pending.length} pending</b></div><p className="submit-status" aria-live="polite">{message}</p>{loading && <p>Loading submissions…</p>}{!loading && !pending.length && <div className="queue-empty">Nothing is waiting for review.</div>}<div className="submission-grid">{pending.map((item) => <article className="submission-card" key={item.id}><img src={`/api/media/${encodeURIComponent(item.photoKey)}`} alt="Submitted evidence"/><div className="submission-body"><small>{item.submissionType === "stock_change" ? "STOCK USED / REMOVED" : item.recordType.replace("_", " ").toUpperCase()}</small><h3>{item.itemName}</h3><p>{item.description || "No additional description."}</p>{item.quantity && <p><b>Reported change:</b> {item.quantity} {item.quantityUnit}</p>}<dl><div><dt>Category</dt><dd>{item.category}</dd></div><div><dt>GPS accuracy</dt><dd>{item.gpsAccuracy ? `±${Math.round(item.gpsAccuracy)} m` : "Not reported"}</dd></div><div><dt>Contributor</dt><dd>{item.contactName}</dd></div><div><dt>{item.contactMethod.replace("_", " ")}</dt><dd>{item.contactValue}</dd></div></dl><a target="_blank" rel="noreferrer" href={`https://www.openstreetmap.org/?mlat=${item.latitude}&mlon=${item.longitude}#map=19/${item.latitude}/${item.longitude}`}>Review exact pin ↗</a><label>Administrator note<textarea id={`note-${item.id}`} rows={2}/></label><div className="decision-row"><button className="reject" onClick={() => decide(item, "rejected")}>Reject</button><button className="approve" onClick={() => decide(item, "approved")}>Approve</button></div></div></article>)}</div>{history.length > 0 && <details className="review-history"><summary>Reviewed submissions ({history.length})</summary>{history.map((item) => <p key={item.id}><b>{item.itemName}</b> — {item.status}</p>)}</details>}</section>;
}
